### PR TITLE
Fix/251 give voting perms to non member

### LINKED ISSUE #251: It should be possible to grant voting permissions to a user if generalforsamlingen would like to do so
There might be people who are not marked as members by OW4 due to our check requires you to study informatics. The board of directors might have overruled this for certain people, and they could therefore be members of the organisation without being members on the webpage.

"Generalforsamlingen" can also overrule the statutes for who are allowed to vote.

### PR DESCRIPTION
**Pull request by sklirg**
Resolves #251

### CODE REVIEW

File: client/src/components/Admin/Users/User.js [hunk 1]
```diff
@@ -67,7 +106,18 @@ User.propTypes = {
...
   registered: PropTypes.string.isRequired,
+  setPermissions: PropTypes.func.isRequired,
   toggleCanVote: PropTypes.func.isRequired,
 };
 
+const mapDispatchToProps = dispatch => ({
+  setPermissions: (id, canVote, permissions) => {
+    dispatch(adminSetPermissions(id, canVote, permissions));
+  },
+});
```
Comment (duvholt) [inline client/src/components/Admin/Users/User.js]: For future reference:  mapDispatchToProps can be an object with actionCreators. 
Meaning that this can be written like this:

```javascript
const mapDispatchToProps = ({
  setPermissions: adminSetPermissions,
});
```

File: server/channels/admin/user/toggle_vote.js [hunk 2]
```diff
@@ -46,13 +53,36 @@ const toggleCanVote = async (socket, data) => {
...
+  const adminUser = await socket.request.user();
+  const { permissions, id: userId } = data;
+
+  try {
+    if (await !canEdit(IS_MANAGER, adminUser, await getActiveGenfors())) {
+      emitError(socket, new Error('Du har ikke rettigheter til å oppdatere andres rettigheter'));
+      return;
+    }
+    const updatedUser = await setUserPermissions(userId, permissions);
+    adminBroadcastAndEmit(socket, ADD_USER, updatedUser);
```
Comment (duvholt) [inline server/channels/admin/user/toggle_vote.js]: Wrap updatedUser in `publicUser(updatedUser, true)`.
