### PR TITLE
Minor UI fixes

### LINKED ISSUE #307: Log in button says "Complete registration" if re-authenticating on a new device
Other (probably) relevant factors:

* Registration was closed

### PR DESCRIPTION
**Pull request by torjusti**
Fixes #307 and begins work on the user admin table. Also fixes some minor pet peeves of mine, like it not being possible to sign into the ACP using the enter button.

### CODE REVIEW

File: client/src/components/Admin/AdminLogin.js [hunk 1]
```diff
@@ -24,6 +24,7 @@ class AdminLogin extends React.Component {
   }
 
   authenticateAdmin(e) {
+    console.log('wtf')
```
Comment (sklirg) [inline client/src/components/Admin/AdminLogin.js]: Smooth

File: client/src/components/Admin/AdminLogin.js [hunk 2]
```diff
@@ -50,43 +51,58 @@ class AdminLogin extends React.Component {
...
-              </form>
-              <Button
-                background
-                size="lg"
-                onClick={e => this.authenticateAdmin(e)}
-              >
-                Logg inn
-              </Button>
+
+              {(!this.props.loggedIn || this.props.loggedIn && this.props.meetingExists) && (
```
Comment (sklirg) [inline client/src/components/Admin/AdminLogin.js]: I'm a fan of parenthesis if the statement could be unclear, i.e. `!loggedIn || (loggedIn && meetingExists)`

File: client/src/components/Admin/AdminLogin.js (hunk 1 above)
Comment (torjusti) [reply client/src/components/Admin/AdminLogin.js]: Super professional :heart_eyes:
